# Generated by Django 2.1.1 on 2018-09-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_initial', models.TimeField(help_text='format to hour 00:00:00')),
                ('hour_finish', models.TimeField(help_text='format to hour 00:00:00')),
                ('quorum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_ubication', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('scheduler', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.States'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='supplies',
            field=models.ManyToManyField(to='rooms.Supplies'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='state',
            field=models.ForeignKey(default=4, editable=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.States'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='supplies',
            field=models.ManyToManyField(to='rooms.Supplies'),
        ),
    ]
